DELETE FROM Funcionarios_OS;
DELETE FROM Pecas_OS;
DELETE FROM Itens_Servico_OS;
DELETE FROM Ordens_de_Servico;
DELETE FROM Funcionarios;
DELETE FROM Cliente_Juridico;
DELETE FROM Cliente_Fisico;
DELETE FROM Enderecos;
DELETE FROM Veiculos;
DELETE FROM Pessoas;
DELETE FROM Servicos;
DELETE FROM Pecas_Estoque;

DBCC CHECKIDENT ('Funcionarios_OS', RESEED, 0);
DBCC CHECKIDENT ('Pecas_OS', RESEED, 0);
DBCC CHECKIDENT ('Itens_Servico_OS', RESEED, 0);
DBCC CHECKIDENT ('Ordens_de_Servico', RESEED, 0);
DBCC CHECKIDENT ('Enderecos', RESEED, 0);
DBCC CHECKIDENT ('Veiculos', RESEED, 0);
DBCC CHECKIDENT ('Pessoas', RESEED, 0);
DBCC CHECKIDENT ('Servicos', RESEED, 0);
DBCC CHECKIDENT ('Pecas_Estoque', RESEED, 0);
PRINT 'Contadores de ID reiniciados.';